
MODULE DEV_ALLOC_MODULE


#define USE_DEV_MALLOC

USE PARKIND1

#ifdef USE_DEV_MALLOC
USE ISO_C_BINDING
#endif

USE PARKIND1

IMPLICIT NONE

INTERFACE DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_1RD_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_2RD_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_3RD_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_4RD_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_5RD_DEV_ALLOCATE_HST
END INTERFACE

INTERFACE DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_1RD_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_2RD_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_3RD_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_4RD_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_5RD_DEV_ALLOCATE_DIM
END INTERFACE

INTERFACE DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_1RD_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_2RD_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_3RD_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_4RD_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_5RD_DEV_DEALLOCATE
END INTERFACE

#ifdef USE_DEV_MALLOC
INTERFACE
  SUBROUTINE DEV_MALLOC (SIZ, PTR) BIND (C, NAME='dev_malloc')
    IMPORT :: C_PTR, C_SIZE_T
    INTEGER (C_SIZE_T), VALUE, INTENT(IN) :: SIZ
    TYPE (C_PTR), INTENT(OUT) :: PTR
  END SUBROUTINE
  SUBROUTINE DEV_FREE (PTR) BIND (C, NAME='dev_free')
    IMPORT :: C_PTR
    TYPE (C_PTR), VALUE, INTENT(IN) :: PTR
  END SUBROUTINE
END INTERFACE
#endif

CONTAINS



#ifndef USE_DEV_MALLOC

SUBROUTINE FIELD_1RD_DEV_ALLOCATE_HST (DEV, HST)

REAL(KIND=JPRD), POINTER :: DEV(:)
REAL(KIND=JPRD), POINTER :: HST(:)

#if __INTEL_COMPILER == 1800 && __INTEL_COMPILER_UPDATE == 5
! Bug with Intel 18.0.5.274
ALLOCATE (DEV (LBOUND (HST, 1):UBOUND (HST,1)))
#else
ALLOCATE (DEV, MOLD=HST)
#endif

!$acc enter data create (DEV)

END SUBROUTINE FIELD_1RD_DEV_ALLOCATE_HST

SUBROUTINE FIELD_1RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS)

REAL(KIND=JPRD), POINTER :: DEV(:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (1)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (1)
INTEGER (KIND=JPIM) :: ILBOUNDS (1)

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

ALLOCATE (DEV (ILBOUNDS (1):UBOUNDS (1)))

!$acc enter data create (DEV)

END SUBROUTINE FIELD_1RD_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_1RD_DEV_DEALLOCATE (DEV)

REAL(KIND=JPRD), POINTER :: DEV(:)
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN
  !$acc exit data delete (DEV)
  DEALLOCATE (DEV)
  PTR = C_LOC (DEV (LBOUND (DEV, 1)))
  CALL DEV_FREE (PTR)
  NULLIFY (DEV)
ENDIF

END SUBROUTINE FIELD_1RD_DEV_DEALLOCATE

#else

SUBROUTINE FIELD_1RD_DEV_ALLOCATE_HST (DEV, HST)

REAL(KIND=JPRD), POINTER :: DEV(:)
REAL(KIND=JPRD), POINTER :: HST(:)

INTEGER :: ILBOUNDS (1)
INTEGER :: IUBOUNDS (1)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_1RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS)

END SUBROUTINE FIELD_1RD_DEV_ALLOCATE_HST

SUBROUTINE FIELD_1RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS)

REAL(KIND=JPRD), POINTER :: DEV(:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (1)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (1)
INTEGER (KIND=JPIM) :: ILBOUNDS (1)
REAL(KIND=JPRD), POINTER :: TMP(:)

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)

CALL DEV_MALLOC (SIZ, PTR)
CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):) => TMP

!$acc enter data create (DEV)

END SUBROUTINE FIELD_1RD_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_1RD_DEV_DEALLOCATE (DEV)

REAL(KIND=JPRD), POINTER :: DEV(:)
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN
  !$acc exit data delete (DEV)
  PTR = C_LOC (DEV (LBOUND (DEV, 1)))
  CALL DEV_FREE (PTR)
  NULLIFY (DEV)
ENDIF

END SUBROUTINE FIELD_1RD_DEV_DEALLOCATE

#endif


#ifndef USE_DEV_MALLOC

SUBROUTINE FIELD_2RD_DEV_ALLOCATE_HST (DEV, HST)

REAL(KIND=JPRD), POINTER :: DEV(:,:)
REAL(KIND=JPRD), POINTER :: HST(:,:)

#if __INTEL_COMPILER == 1800 && __INTEL_COMPILER_UPDATE == 5
! Bug with Intel 18.0.5.274
ALLOCATE (DEV (LBOUND (HST, 1):UBOUND (HST,1), LBOUND (HST, 2):UBOUND (HST,2)))
#else
ALLOCATE (DEV, MOLD=HST)
#endif

!$acc enter data create (DEV)

END SUBROUTINE FIELD_2RD_DEV_ALLOCATE_HST

SUBROUTINE FIELD_2RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS)

REAL(KIND=JPRD), POINTER :: DEV(:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (2)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)
INTEGER (KIND=JPIM) :: ILBOUNDS (2)

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

ALLOCATE (DEV (ILBOUNDS (1):UBOUNDS (1), ILBOUNDS (2):UBOUNDS (2)))

!$acc enter data create (DEV)

END SUBROUTINE FIELD_2RD_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_2RD_DEV_DEALLOCATE (DEV)

REAL(KIND=JPRD), POINTER :: DEV(:,:)
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN
  !$acc exit data delete (DEV)
  DEALLOCATE (DEV)
  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2)))
  CALL DEV_FREE (PTR)
  NULLIFY (DEV)
ENDIF

END SUBROUTINE FIELD_2RD_DEV_DEALLOCATE

#else

SUBROUTINE FIELD_2RD_DEV_ALLOCATE_HST (DEV, HST)

REAL(KIND=JPRD), POINTER :: DEV(:,:)
REAL(KIND=JPRD), POINTER :: HST(:,:)

INTEGER :: ILBOUNDS (2)
INTEGER :: IUBOUNDS (2)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_2RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS)

END SUBROUTINE FIELD_2RD_DEV_ALLOCATE_HST

SUBROUTINE FIELD_2RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS)

REAL(KIND=JPRD), POINTER :: DEV(:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (2)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)
INTEGER (KIND=JPIM) :: ILBOUNDS (2)
REAL(KIND=JPRD), POINTER :: TMP(:,:)

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(2)-ILBOUNDS(2)+1, C_SIZE_T)

CALL DEV_MALLOC (SIZ, PTR)
CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):, ILBOUNDS (2):) => TMP

!$acc enter data create (DEV)

END SUBROUTINE FIELD_2RD_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_2RD_DEV_DEALLOCATE (DEV)

REAL(KIND=JPRD), POINTER :: DEV(:,:)
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN
  !$acc exit data delete (DEV)
  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2)))
  CALL DEV_FREE (PTR)
  NULLIFY (DEV)
ENDIF

END SUBROUTINE FIELD_2RD_DEV_DEALLOCATE

#endif


#ifndef USE_DEV_MALLOC

SUBROUTINE FIELD_3RD_DEV_ALLOCATE_HST (DEV, HST)

REAL(KIND=JPRD), POINTER :: DEV(:,:,:)
REAL(KIND=JPRD), POINTER :: HST(:,:,:)

#if __INTEL_COMPILER == 1800 && __INTEL_COMPILER_UPDATE == 5
! Bug with Intel 18.0.5.274
ALLOCATE (DEV (LBOUND (HST, 1):UBOUND (HST,1), LBOUND (HST, 2):UBOUND (HST,2), LBOUND (HST, 3):UBOUND (HST,3)))
#else
ALLOCATE (DEV, MOLD=HST)
#endif

!$acc enter data create (DEV)

END SUBROUTINE FIELD_3RD_DEV_ALLOCATE_HST

SUBROUTINE FIELD_3RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS)

REAL(KIND=JPRD), POINTER :: DEV(:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (3)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (3)
INTEGER (KIND=JPIM) :: ILBOUNDS (3)

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

ALLOCATE (DEV (ILBOUNDS (1):UBOUNDS (1), ILBOUNDS (2):UBOUNDS (2), ILBOUNDS (3):UBOUNDS (3)))

!$acc enter data create (DEV)

END SUBROUTINE FIELD_3RD_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_3RD_DEV_DEALLOCATE (DEV)

REAL(KIND=JPRD), POINTER :: DEV(:,:,:)
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN
  !$acc exit data delete (DEV)
  DEALLOCATE (DEV)
  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2), LBOUND (DEV, 3)))
  CALL DEV_FREE (PTR)
  NULLIFY (DEV)
ENDIF

END SUBROUTINE FIELD_3RD_DEV_DEALLOCATE

#else

SUBROUTINE FIELD_3RD_DEV_ALLOCATE_HST (DEV, HST)

REAL(KIND=JPRD), POINTER :: DEV(:,:,:)
REAL(KIND=JPRD), POINTER :: HST(:,:,:)

INTEGER :: ILBOUNDS (3)
INTEGER :: IUBOUNDS (3)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_3RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS)

END SUBROUTINE FIELD_3RD_DEV_ALLOCATE_HST

SUBROUTINE FIELD_3RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS)

REAL(KIND=JPRD), POINTER :: DEV(:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (3)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (3)
INTEGER (KIND=JPIM) :: ILBOUNDS (3)
REAL(KIND=JPRD), POINTER :: TMP(:,:,:)

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(2)-ILBOUNDS(2)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(3)-ILBOUNDS(3)+1, C_SIZE_T)

CALL DEV_MALLOC (SIZ, PTR)
CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):, ILBOUNDS (2):, ILBOUNDS (3):) => TMP

!$acc enter data create (DEV)

END SUBROUTINE FIELD_3RD_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_3RD_DEV_DEALLOCATE (DEV)

REAL(KIND=JPRD), POINTER :: DEV(:,:,:)
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN
  !$acc exit data delete (DEV)
  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2), LBOUND (DEV, 3)))
  CALL DEV_FREE (PTR)
  NULLIFY (DEV)
ENDIF

END SUBROUTINE FIELD_3RD_DEV_DEALLOCATE

#endif


#ifndef USE_DEV_MALLOC

SUBROUTINE FIELD_4RD_DEV_ALLOCATE_HST (DEV, HST)

REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:)
REAL(KIND=JPRD), POINTER :: HST(:,:,:,:)

#if __INTEL_COMPILER == 1800 && __INTEL_COMPILER_UPDATE == 5
! Bug with Intel 18.0.5.274
ALLOCATE (DEV (LBOUND (HST, 1):UBOUND (HST,1), LBOUND (HST, 2):UBOUND (HST,2), LBOUND (HST, 3):UBOUND (HST,3), LBOUND (HST,&
    & 4):UBOUND (HST,4)))
#else
ALLOCATE (DEV, MOLD=HST)
#endif

!$acc enter data create (DEV)

END SUBROUTINE FIELD_4RD_DEV_ALLOCATE_HST

SUBROUTINE FIELD_4RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS)

REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (4)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (4)
INTEGER (KIND=JPIM) :: ILBOUNDS (4)

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

ALLOCATE (DEV (ILBOUNDS (1):UBOUNDS (1), ILBOUNDS (2):UBOUNDS (2), ILBOUNDS (3):UBOUNDS (3), ILBOUNDS (4):UBOUNDS (4)))

!$acc enter data create (DEV)

END SUBROUTINE FIELD_4RD_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_4RD_DEV_DEALLOCATE (DEV)

REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:)
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN
  !$acc exit data delete (DEV)
  DEALLOCATE (DEV)
  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2), LBOUND (DEV, 3), LBOUND (DEV, 4)))
  CALL DEV_FREE (PTR)
  NULLIFY (DEV)
ENDIF

END SUBROUTINE FIELD_4RD_DEV_DEALLOCATE

#else

SUBROUTINE FIELD_4RD_DEV_ALLOCATE_HST (DEV, HST)

REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:)
REAL(KIND=JPRD), POINTER :: HST(:,:,:,:)

INTEGER :: ILBOUNDS (4)
INTEGER :: IUBOUNDS (4)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_4RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS)

END SUBROUTINE FIELD_4RD_DEV_ALLOCATE_HST

SUBROUTINE FIELD_4RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS)

REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (4)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (4)
INTEGER (KIND=JPIM) :: ILBOUNDS (4)
REAL(KIND=JPRD), POINTER :: TMP(:,:,:,:)

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(2)-ILBOUNDS(2)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(3)-ILBOUNDS(3)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(4)-ILBOUNDS(4)+1, C_SIZE_T)

CALL DEV_MALLOC (SIZ, PTR)
CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):, ILBOUNDS (2):, ILBOUNDS (3):, ILBOUNDS (4):) => TMP

!$acc enter data create (DEV)

END SUBROUTINE FIELD_4RD_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_4RD_DEV_DEALLOCATE (DEV)

REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:)
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN
  !$acc exit data delete (DEV)
  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2), LBOUND (DEV, 3), LBOUND (DEV, 4)))
  CALL DEV_FREE (PTR)
  NULLIFY (DEV)
ENDIF

END SUBROUTINE FIELD_4RD_DEV_DEALLOCATE

#endif


#ifndef USE_DEV_MALLOC

SUBROUTINE FIELD_5RD_DEV_ALLOCATE_HST (DEV, HST)

REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:,:)
REAL(KIND=JPRD), POINTER :: HST(:,:,:,:,:)

#if __INTEL_COMPILER == 1800 && __INTEL_COMPILER_UPDATE == 5
! Bug with Intel 18.0.5.274
ALLOCATE (DEV (LBOUND (HST, 1):UBOUND (HST,1), LBOUND (HST, 2):UBOUND (HST,2), LBOUND (HST, 3):UBOUND (HST,3), LBOUND (HST,&
    & 4):UBOUND (HST,4), LBOUND (HST, 5):UBOUND (HST,5)))
#else
ALLOCATE (DEV, MOLD=HST)
#endif

!$acc enter data create (DEV)

END SUBROUTINE FIELD_5RD_DEV_ALLOCATE_HST

SUBROUTINE FIELD_5RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS)

REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (5)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (5)
INTEGER (KIND=JPIM) :: ILBOUNDS (5)

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

ALLOCATE (DEV (ILBOUNDS (1):UBOUNDS (1), ILBOUNDS (2):UBOUNDS (2), ILBOUNDS (3):UBOUNDS (3), ILBOUNDS (4):UBOUNDS (4), ILBOUNDS&
    & (5):UBOUNDS (5)))

!$acc enter data create (DEV)

END SUBROUTINE FIELD_5RD_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_5RD_DEV_DEALLOCATE (DEV)

REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:,:)
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN
  !$acc exit data delete (DEV)
  DEALLOCATE (DEV)
  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2), LBOUND (DEV, 3), LBOUND (DEV, 4), LBOUND (DEV, 5)))
  CALL DEV_FREE (PTR)
  NULLIFY (DEV)
ENDIF

END SUBROUTINE FIELD_5RD_DEV_DEALLOCATE

#else

SUBROUTINE FIELD_5RD_DEV_ALLOCATE_HST (DEV, HST)

REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:,:)
REAL(KIND=JPRD), POINTER :: HST(:,:,:,:,:)

INTEGER :: ILBOUNDS (5)
INTEGER :: IUBOUNDS (5)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_5RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS)

END SUBROUTINE FIELD_5RD_DEV_ALLOCATE_HST

SUBROUTINE FIELD_5RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS)

REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (5)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (5)
INTEGER (KIND=JPIM) :: ILBOUNDS (5)
REAL(KIND=JPRD), POINTER :: TMP(:,:,:,:,:)

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(2)-ILBOUNDS(2)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(3)-ILBOUNDS(3)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(4)-ILBOUNDS(4)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(5)-ILBOUNDS(5)+1, C_SIZE_T)

CALL DEV_MALLOC (SIZ, PTR)
CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):, ILBOUNDS (2):, ILBOUNDS (3):, ILBOUNDS (4):, ILBOUNDS (5):) => TMP

!$acc enter data create (DEV)

END SUBROUTINE FIELD_5RD_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_5RD_DEV_DEALLOCATE (DEV)

REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:,:)
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN
  !$acc exit data delete (DEV)
  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2), LBOUND (DEV, 3), LBOUND (DEV, 4), LBOUND (DEV, 5)))
  CALL DEV_FREE (PTR)
  NULLIFY (DEV)
ENDIF

END SUBROUTINE FIELD_5RD_DEV_DEALLOCATE

#endif


END MODULE DEV_ALLOC_MODULE
