
MODULE FIELD_4RD_GANG_MODULE



USE FIELD_BASIC_MODULE
USE FIELD_4RD_MODULE
USE DEV_ALLOC_MODULE

USE PARKIND1

IMPLICIT NONE

TYPE, EXTENDS (FIELD_4RD_WRAPPER) :: FIELD_4RD_GANG_WRAPPER
CONTAINS
  PROCEDURE :: INIT => FIELD_4RD_GANG_WRAPPER_INIT
  PROCEDURE :: FINAL => FIELD_4RD_GANG_WRAPPER_FINAL
  PROCEDURE :: CREATE_DEVICE_DATA => FIELD_4RD_GANG_WRAPPER_CREATE_DEVICE_DATA
  PROCEDURE :: DELETE_DEVICE_DATA => FIELD_4RD_GANG_WRAPPER_DELETE_DEVICE_DATA
  PROCEDURE :: SET_STATUS => FIELD_4RD_GANG_WRAPPER_SET_STATUS
END TYPE FIELD_4RD_GANG_WRAPPER

PUBLIC :: FIELD_4RD_GANG_WRAPPER


TYPE, EXTENDS (FIELD_4RD_OWNER) :: FIELD_4RD_GANG_OWNER
CONTAINS
  PROCEDURE :: INIT => FIELD_4RD_GANG_OWNER_INIT
  PROCEDURE :: FINAL => FIELD_4RD_GANG_OWNER_FINAL
  PROCEDURE :: CREATE_DEVICE_DATA => FIELD_4RD_GANG_OWNER_CREATE_DEVICE_DATA
  PROCEDURE :: DELETE_DEVICE_DATA => FIELD_4RD_GANG_OWNER_DELETE_DEVICE_DATA
  PROCEDURE :: SET_STATUS => FIELD_4RD_GANG_OWNER_SET_STATUS
END TYPE FIELD_4RD_GANG_OWNER

PUBLIC :: FIELD_4RD_GANG_OWNER


CONTAINS

  SUBROUTINE FIELD_4RD_GANG_WRAPPER_INIT(SELF, DATA, PERSISTENT, LBOUNDS)
    CLASS(FIELD_4RD_GANG_WRAPPER) :: SELF
    REAL(KIND=JPRD), TARGET, INTENT(IN) :: DATA(:,:,:,:)
    LOGICAL, INTENT(IN), OPTIONAL :: PERSISTENT
    INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: LBOUNDS(4)
    LOGICAL :: LLPERSISTENT
    INTEGER (KIND=JPIM) :: IFLR, JFLD, NFLD
    INTEGER (KIND=JPIM) :: LLBOUNDS (4)

  
    CALL SELF%FIELD_4RD_WRAPPER%INIT (DATA=DATA, PERSISTENT=PERSISTENT, LBOUNDS=LBOUNDS)

    LLBOUNDS = 1
    IF (PRESENT (LBOUNDS)) LLBOUNDS = LBOUNDS

    IFLR = 4-1
    NFLD = SIZE (DATA, IFLR)

    LLBOUNDS(IFLR) = LLBOUNDS (IFLR+1)
    

  END SUBROUTINE FIELD_4RD_GANG_WRAPPER_INIT

  SUBROUTINE FIELD_4RD_GANG_OWNER_INIT(SELF, LBOUNDS, UBOUNDS, PERSISTENT, DELAYED, INIT_VALUE)
    CLASS(FIELD_4RD_GANG_OWNER) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: LBOUNDS(4)
    INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(4)
    LOGICAL, INTENT(IN), OPTIONAL :: PERSISTENT
    LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED
    REAL(KIND=JPRD), OPTIONAL, INTENT(IN) :: INIT_VALUE
    LOGICAL :: LLPERSISTENT
    INTEGER (KIND=JPIM) :: IFLR, JFLD, NFLD
    INTEGER (KIND=JPIM) :: LLBOUNDS (4)

    CALL SELF%FIELD_4RD_OWNER%INIT (PERSISTENT=PERSISTENT, LBOUNDS=LBOUNDS, UBOUNDS=UBOUNDS, DELAYED=.FALSE., INIT_VALUE=INIT_VALUE)

    LLBOUNDS = 1
    IF (PRESENT (LBOUNDS)) LLBOUNDS = LBOUNDS

    IFLR = 4-1
    NFLD = UBOUNDS (IFLR)-LLBOUNDS (IFLR)+1

    LLBOUNDS(IFLR) = LLBOUNDS (IFLR+1)

  END SUBROUTINE FIELD_4RD_GANG_OWNER_INIT

  SUBROUTINE FIELD_4RD_GANG_WRAPPER_FINAL(SELF)
    CLASS(FIELD_4RD_GANG_WRAPPER) :: SELF
    REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:)
    INTEGER (KIND=JPIM) :: JFLD

    CALL SELF%FIELD_4RD_WRAPPER%FINAL ()

  END SUBROUTINE FIELD_4RD_GANG_WRAPPER_FINAL

  SUBROUTINE FIELD_4RD_GANG_WRAPPER_DELETE_DEVICE_DATA(SELF)
    ! Delete the copy of this field on GPU device
    CLASS(FIELD_4RD_GANG_WRAPPER) :: SELF

    INTEGER (KIND=JPIM) :: JFLD

  END SUBROUTINE FIELD_4RD_GANG_WRAPPER_DELETE_DEVICE_DATA

  SUBROUTINE FIELD_4RD_GANG_WRAPPER_CREATE_DEVICE_DATA (SELF)
    CLASS(FIELD_4RD_GANG_WRAPPER) :: SELF
    INTEGER (KIND=JPIM) :: JFLD

    CALL SELF%FIELD_4RD_WRAPPER%CREATE_DEVICE_DATA ()

  END SUBROUTINE

  SUBROUTINE FIELD_4RD_GANG_WRAPPER_SET_STATUS (SELF, KSTATUS)
    CLASS(FIELD_4RD_GANG_WRAPPER) :: SELF
    INTEGER (KIND=JPIM), INTENT (IN) :: KSTATUS

    INTEGER (KIND=JPIM) :: JFLD

WRITE (0, *) __FILE__, ':', __LINE__, " SET_STATUS = ", KSTATUS

    CALL SELF%FIELD_4RD_WRAPPER%SET_STATUS (KSTATUS)

  END SUBROUTINE

  SUBROUTINE FIELD_4RD_GANG_OWNER_FINAL(SELF)
    CLASS(FIELD_4RD_GANG_OWNER) :: SELF
    REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:)
    INTEGER (KIND=JPIM) :: JFLD

    CALL SELF%FIELD_4RD_OWNER%FINAL ()

  END SUBROUTINE FIELD_4RD_GANG_OWNER_FINAL

  SUBROUTINE FIELD_4RD_GANG_OWNER_DELETE_DEVICE_DATA(SELF)
    ! Delete the copy of this field on GPU device
    CLASS(FIELD_4RD_GANG_OWNER) :: SELF

    INTEGER (KIND=JPIM) :: JFLD

  END SUBROUTINE FIELD_4RD_GANG_OWNER_DELETE_DEVICE_DATA

  SUBROUTINE FIELD_4RD_GANG_OWNER_CREATE_DEVICE_DATA (SELF)
    CLASS(FIELD_4RD_GANG_OWNER) :: SELF
    INTEGER (KIND=JPIM) :: JFLD

    CALL SELF%FIELD_4RD_OWNER%CREATE_DEVICE_DATA ()

  END SUBROUTINE

  SUBROUTINE FIELD_4RD_GANG_OWNER_SET_STATUS (SELF, KSTATUS)
    CLASS(FIELD_4RD_GANG_OWNER) :: SELF
    INTEGER (KIND=JPIM), INTENT (IN) :: KSTATUS

    INTEGER (KIND=JPIM) :: JFLD

WRITE (0, *) __FILE__, ':', __LINE__, " SET_STATUS = ", KSTATUS

    CALL SELF%FIELD_4RD_OWNER%SET_STATUS (KSTATUS)

  END SUBROUTINE



END MODULE FIELD_4RD_GANG_MODULE
