MODULE FIELD_4RD_GANG_MODULE

USE FIELD_BASIC_MODULE
USE FIELD_4RD_MODULE

USE PARKIND1

IMPLICIT NONE

TYPE, EXTENDS (FIELD_4RD_OWNER) :: FIELD_4RD_GANG_OWNER
CONTAINS
  PROCEDURE :: SET_STATUS => FIELD_4RD_GANG_OWNER_SET_STATUS
END TYPE FIELD_4RD_GANG_OWNER

CONTAINS

  SUBROUTINE FIELD_4RD_GANG_OWNER_SET_STATUS (SELF, KSTATUS)
    CLASS(FIELD_4RD_GANG_OWNER) :: SELF
    INTEGER (KIND=JPIM), INTENT (IN) :: KSTATUS

WRITE (0, *) __FILE__, ':', __LINE__, " SET_STATUS = ", KSTATUS

    CALL SELF%FIELD_4RD_OWNER%SET_STATUS (KSTATUS)

  END SUBROUTINE



END MODULE FIELD_4RD_GANG_MODULE
