! (C) Copyright 2022- ECMWF.
! (C) Copyright 2022- Meteo-France.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE FIELD_BASIC_MODULE

USE PARKIND1, ONLY : JPIM

IMPLICIT NONE

INTEGER (KIND=JPIM), PARAMETER :: NDEVFRESH =      INT(B'00000001', KIND=JPIM)
INTEGER (KIND=JPIM), PARAMETER :: NHSTFRESH =      INT(B'00000010', KIND=JPIM)
INTEGER (KIND=JPIM), PARAMETER :: UNALLOCATED =    INT(B'00000100', KIND=JPIM)
INTEGER (KIND=JPIM), PARAMETER :: UNINITIALIZED =  INT(B'00000011', KIND=JPIM)
INTEGER (KIND=JPIM), PARAMETER :: NH2D = 1, ND2H = 2
INTEGER (KIND=JPIM), PARAMETER :: NRD = INT(B'00000001', KIND=JPIM)
INTEGER (KIND=JPIM), PARAMETER :: NWR = INT(B'00000010', KIND=JPIM)

TYPE, ABSTRACT :: FIELD_BASIC
  CLASS (FIELD_BASIC), POINTER :: PARENT => NULL ()
  LOGICAL :: THREAD_BUFFER = .FALSE.

  INTEGER(KIND=JPIM) :: ISTATUS = 0
  INTEGER(KIND=JPIM) :: LAST_CONTIGUOUS_DIMENSION = 0

  LOGICAL :: LOBJECT_COPIED = .FALSE.

CONTAINS
! PROCEDURE (FIELD_BASIC_SYNC),   DEFERRED :: SYNC_HOST_RDWR
! PROCEDURE (FIELD_BASIC_SYNC),   DEFERRED :: SYNC_HOST_RDONLY
! PROCEDURE (FIELD_BASIC_SYNC),   DEFERRED :: SYNC_DEVICE_RDWR
! PROCEDURE (FIELD_BASIC_SYNC),   DEFERRED :: SYNC_DEVICE_RDONLY
! PROCEDURE (FIELD_BASIC_DELETE_DEVICE_DATA), DEFERRED :: DELETE_DEVICE_DATA
! PROCEDURE (FIELD_BASIC_CREATE_DEVICE_DATA), DEFERRED :: CREATE_DEVICE_DATA
! PROCEDURE :: SET_CHILDREN_DEVPTR => FIELD_BASIC_SET_CHILDREN_DEVPTR
! PROCEDURE :: SET_DEVICE_DIRTY => FIELD_BASIC_SET_DEVICE_DIRTY
  PROCEDURE :: SET_STATUS => FIELD_BASIC_SET_STATUS
END TYPE FIELD_BASIC

PUBLIC :: FIELD_BASIC

ABSTRACT INTERFACE
  SUBROUTINE FIELD_BASIC_SYNC (SELF, QUEUE)
    IMPORT FIELD_BASIC
    CLASS(FIELD_BASIC) :: SELF
    INTEGER, OPTIONAL,  INTENT(IN)    :: QUEUE
  END SUBROUTINE
  SUBROUTINE FIELD_BASIC_DELETE_DEVICE_DATA (SELF)
    IMPORT FIELD_BASIC
    CLASS(FIELD_BASIC) :: SELF
  END SUBROUTINE
  SUBROUTINE FIELD_BASIC_CREATE_DEVICE_DATA (SELF)
    IMPORT FIELD_BASIC
    CLASS(FIELD_BASIC) :: SELF
  END SUBROUTINE
END INTERFACE

PUBLIC :: FIELD_BASIC_SYNC

CONTAINS

SUBROUTINE FIELD_BASIC_SET_STATUS (SELF, KSTATUS)

CLASS (FIELD_BASIC) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: KSTATUS

SELF%ISTATUS = KSTATUS

END SUBROUTINE FIELD_BASIC_SET_STATUS

END MODULE FIELD_BASIC_MODULE
