
MODULE FIELD_MODULE


USE DEV_ALLOC_MODULE

USE FIELD_4RD_MODULE

USE PARKIND1

IMPLICIT NONE

PRIVATE

PUBLIC :: FIELD_4RD
PUBLIC :: FIELD_4RD_OWNER
PUBLIC :: FIELD_4RD_WRAPPER
PUBLIC :: FIELD_4RD_PTR
PUBLIC :: FIELD_4RD_VIEW

PUBLIC :: WAIT_FOR_ASYNC_QUEUE

CONTAINS

  SUBROUTINE WAIT_FOR_ASYNC_QUEUE(QUEUE)
    INTEGER(KIND=JPIM), INTENT(IN) :: QUEUE
    !Wait for all data transfer initiated on queue by the current thread
!$acc wait (QUEUE)
  END SUBROUTINE WAIT_FOR_ASYNC_QUEUE

END MODULE FIELD_MODULE
