
MODULE FIELD_4RD_MODULE


USE OML_MOD, ONLY: OML_MAX_THREADS , OML_MY_THREAD
USE IEEE_ARITHMETIC, ONLY: IEEE_SIGNALING_NAN
USE FIELD_BASIC_MODULE
USE PARKIND1

IMPLICIT NONE

TYPE, ABSTRACT, EXTENDS (FIELD_BASIC) :: FIELD_4RD
  REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:) => NULL()
  REAL(KIND=JPRD), POINTER, CONTIGUOUS :: DEVPTR(:,:,:,:) => NULL()
CONTAINS

END TYPE FIELD_4RD

ABSTRACT INTERFACE
  SUBROUTINE GET_DIMS(SELF, LBOUNDS, UBOUNDS)
    USE PARKIND1
    IMPORT ::  FIELD_4RD
    CLASS(FIELD_4RD),               INTENT(IN) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT) :: LBOUNDS(4)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT) :: UBOUNDS(4)
  END SUBROUTINE GET_DIMS
  SUBROUTINE RESIZE (SELF, UBOUNDS, LBOUNDS, PERSISTENT)
    USE PARKIND1
    IMPORT ::  FIELD_4RD
    CLASS(FIELD_4RD),               INTENT(IN) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: UBOUNDS(4)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS(4)
    LOGICAL, OPTIONAL,            INTENT(IN) :: PERSISTENT
  END SUBROUTINE RESIZE
END INTERFACE

PUBLIC :: FIELD_4RD

TYPE, EXTENDS(FIELD_4RD) :: FIELD_4RD_OWNER
  INTEGER(KIND=JPIM) :: LBOUNDS(4), UBOUNDS(4)
  LOGICAL :: HAS_INIT_VALUE = .FALSE.
  REAL(KIND=JPRD) :: INIT_VALUE
CONTAINS
END TYPE FIELD_4RD_OWNER

PUBLIC :: FIELD_4RD_OWNER

TYPE FIELD_4RD_PTR
  CLASS(FIELD_4RD), POINTER :: PTR => NULL()
END TYPE FIELD_4RD_PTR

PUBLIC :: FIELD_4RD_PTR

TYPE FIELD_4RD_VIEW
  REAL(KIND=JPRD), POINTER :: P(:,:,:) => NULL()
END TYPE FIELD_4RD_VIEW

PUBLIC :: FIELD_4RD_VIEW


CONTAINS


END MODULE FIELD_4RD_MODULE
